# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import contentos_sdk.grpc_pb2.grpc_pb2 as grpc__pb2


class ApiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryTableContent = channel.unary_unary(
        '/grpcpb.ApiService/QueryTableContent',
        request_serializer=grpc__pb2.GetTableContentRequest.SerializeToString,
        response_deserializer=grpc__pb2.TableContentResponse.FromString,
        )
    self.GetAccountByName = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountByName',
        request_serializer=grpc__pb2.GetAccountByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.AccountResponse.FromString,
        )
    self.GetAccountCashout = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountCashout',
        request_serializer=grpc__pb2.GetAccountCashoutRequest.SerializeToString,
        response_deserializer=grpc__pb2.AccountCashoutResponse.FromString,
        )
    self.GetBlockCashout = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockCashout',
        request_serializer=grpc__pb2.GetBlockCashoutRequest.SerializeToString,
        response_deserializer=grpc__pb2.BlockCashoutResponse.FromString,
        )
    self.GetFollowerListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowerListByName',
        request_serializer=grpc__pb2.GetFollowerListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowerListByNameResponse.FromString,
        )
    self.GetFollowingListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowingListByName',
        request_serializer=grpc__pb2.GetFollowingListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowingListByNameResponse.FromString,
        )
    self.GetFollowCountByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowCountByName',
        request_serializer=grpc__pb2.GetFollowCountByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowCountByNameResponse.FromString,
        )
    self.GetWitnessList = channel.unary_unary(
        '/grpcpb.ApiService/GetWitnessList',
        request_serializer=grpc__pb2.GetWitnessListRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetWitnessListResponse.FromString,
        )
    self.GetPostListByCreated = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByCreated',
        request_serializer=grpc__pb2.GetPostListByCreatedRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreatedResponse.FromString,
        )
    self.GetReplyListByPostId = channel.unary_unary(
        '/grpcpb.ApiService/GetReplyListByPostId',
        request_serializer=grpc__pb2.GetReplyListByPostIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetReplyListByPostIdResponse.FromString,
        )
    self.GetBlockTransactionsByNum = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockTransactionsByNum',
        request_serializer=grpc__pb2.GetBlockTransactionsByNumRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockTransactionsByNumResponse.FromString,
        )
    self.GetChainState = channel.unary_unary(
        '/grpcpb.ApiService/GetChainState',
        request_serializer=grpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetChainStateResponse.FromString,
        )
    self.BroadcastTrx = channel.unary_unary(
        '/grpcpb.ApiService/BroadcastTrx',
        request_serializer=grpc__pb2.BroadcastTrxRequest.SerializeToString,
        response_deserializer=grpc__pb2.BroadcastTrxResponse.FromString,
        )
    self.GetBlockList = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockList',
        request_serializer=grpc__pb2.GetBlockListRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockListResponse.FromString,
        )
    self.GetSignedBlock = channel.unary_unary(
        '/grpcpb.ApiService/GetSignedBlock',
        request_serializer=grpc__pb2.GetSignedBlockRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetSignedBlockResponse.FromString,
        )
    self.GetAccountListByBalance = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountListByBalance',
        request_serializer=grpc__pb2.GetAccountListByBalanceRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAccountListResponse.FromString,
        )
    self.GetDailyTotalTrxInfo = channel.unary_unary(
        '/grpcpb.ApiService/GetDailyTotalTrxInfo',
        request_serializer=grpc__pb2.GetDailyTotalTrxRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetDailyTotalTrxResponse.FromString,
        )
    self.GetTrxInfoById = channel.unary_unary(
        '/grpcpb.ApiService/GetTrxInfoById',
        request_serializer=grpc__pb2.GetTrxInfoByIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetTrxInfoByIdResponse.FromString,
        )
    self.GetTrxListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetTrxListByTime',
        request_serializer=grpc__pb2.GetTrxListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetTrxListByTimeResponse.FromString,
        )
    self.GetPostListByCreateTime = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByCreateTime',
        request_serializer=grpc__pb2.GetPostListByCreateTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreateTimeResponse.FromString,
        )
    self.GetPostListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByName',
        request_serializer=grpc__pb2.GetPostListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreateTimeResponse.FromString,
        )
    self.TrxStatByHour = channel.unary_unary(
        '/grpcpb.ApiService/TrxStatByHour',
        request_serializer=grpc__pb2.TrxStatByHourRequest.SerializeToString,
        response_deserializer=grpc__pb2.TrxStatByHourResponse.FromString,
        )
    self.GetUserTrxListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetUserTrxListByTime',
        request_serializer=grpc__pb2.GetUserTrxListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetUserTrxListByTimeResponse.FromString,
        )
    self.GetPostInfoById = channel.unary_unary(
        '/grpcpb.ApiService/GetPostInfoById',
        request_serializer=grpc__pb2.GetPostInfoByIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostInfoByIdResponse.FromString,
        )
    self.GetContractInfo = channel.unary_unary(
        '/grpcpb.ApiService/GetContractInfo',
        request_serializer=grpc__pb2.GetContractInfoRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetContractInfoResponse.FromString,
        )
    self.GetBlkIsIrreversibleByTxId = channel.unary_unary(
        '/grpcpb.ApiService/GetBlkIsIrreversibleByTxId',
        request_serializer=grpc__pb2.GetBlkIsIrreversibleByTxIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlkIsIrreversibleByTxIdResponse.FromString,
        )
    self.GetAccountListByCreTime = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountListByCreTime',
        request_serializer=grpc__pb2.GetAccountListByCreTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAccountListResponse.FromString,
        )
    self.GetDailyStats = channel.unary_unary(
        '/grpcpb.ApiService/GetDailyStats',
        request_serializer=grpc__pb2.GetDailyStatsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetDailyStatsResponse.FromString,
        )
    self.GetContractListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetContractListByTime',
        request_serializer=grpc__pb2.GetContractListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetContractListResponse.FromString,
        )
    self.GetWitnessListByVoteCount = channel.unary_unary(
        '/grpcpb.ApiService/GetWitnessListByVoteCount',
        request_serializer=grpc__pb2.GetWitnessListByVoteCountRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetWitnessListResponse.FromString,
        )
    self.GetPostListByVest = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByVest',
        request_serializer=grpc__pb2.GetPostListByVestRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByVestResponse.FromString,
        )


class ApiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def QueryTableContent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountCashout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockCashout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowerListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowingListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowCountByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWitnessList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByCreated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReplyListByPostId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockTransactionsByNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChainState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastTrx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSignedBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountListByBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDailyTotalTrxInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrxInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrxListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByCreateTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TrxStatByHour(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserTrxListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlkIsIrreversibleByTxId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountListByCreTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDailyStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWitnessListByVoteCount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByVest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryTableContent': grpc.unary_unary_rpc_method_handler(
          servicer.QueryTableContent,
          request_deserializer=grpc__pb2.GetTableContentRequest.FromString,
          response_serializer=grpc__pb2.TableContentResponse.SerializeToString,
      ),
      'GetAccountByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountByName,
          request_deserializer=grpc__pb2.GetAccountByNameRequest.FromString,
          response_serializer=grpc__pb2.AccountResponse.SerializeToString,
      ),
      'GetAccountCashout': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountCashout,
          request_deserializer=grpc__pb2.GetAccountCashoutRequest.FromString,
          response_serializer=grpc__pb2.AccountCashoutResponse.SerializeToString,
      ),
      'GetBlockCashout': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockCashout,
          request_deserializer=grpc__pb2.GetBlockCashoutRequest.FromString,
          response_serializer=grpc__pb2.BlockCashoutResponse.SerializeToString,
      ),
      'GetFollowerListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowerListByName,
          request_deserializer=grpc__pb2.GetFollowerListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowerListByNameResponse.SerializeToString,
      ),
      'GetFollowingListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowingListByName,
          request_deserializer=grpc__pb2.GetFollowingListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowingListByNameResponse.SerializeToString,
      ),
      'GetFollowCountByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowCountByName,
          request_deserializer=grpc__pb2.GetFollowCountByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowCountByNameResponse.SerializeToString,
      ),
      'GetWitnessList': grpc.unary_unary_rpc_method_handler(
          servicer.GetWitnessList,
          request_deserializer=grpc__pb2.GetWitnessListRequest.FromString,
          response_serializer=grpc__pb2.GetWitnessListResponse.SerializeToString,
      ),
      'GetPostListByCreated': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByCreated,
          request_deserializer=grpc__pb2.GetPostListByCreatedRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreatedResponse.SerializeToString,
      ),
      'GetReplyListByPostId': grpc.unary_unary_rpc_method_handler(
          servicer.GetReplyListByPostId,
          request_deserializer=grpc__pb2.GetReplyListByPostIdRequest.FromString,
          response_serializer=grpc__pb2.GetReplyListByPostIdResponse.SerializeToString,
      ),
      'GetBlockTransactionsByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockTransactionsByNum,
          request_deserializer=grpc__pb2.GetBlockTransactionsByNumRequest.FromString,
          response_serializer=grpc__pb2.GetBlockTransactionsByNumResponse.SerializeToString,
      ),
      'GetChainState': grpc.unary_unary_rpc_method_handler(
          servicer.GetChainState,
          request_deserializer=grpc__pb2.NonParamsRequest.FromString,
          response_serializer=grpc__pb2.GetChainStateResponse.SerializeToString,
      ),
      'BroadcastTrx': grpc.unary_unary_rpc_method_handler(
          servicer.BroadcastTrx,
          request_deserializer=grpc__pb2.BroadcastTrxRequest.FromString,
          response_serializer=grpc__pb2.BroadcastTrxResponse.SerializeToString,
      ),
      'GetBlockList': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockList,
          request_deserializer=grpc__pb2.GetBlockListRequest.FromString,
          response_serializer=grpc__pb2.GetBlockListResponse.SerializeToString,
      ),
      'GetSignedBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetSignedBlock,
          request_deserializer=grpc__pb2.GetSignedBlockRequest.FromString,
          response_serializer=grpc__pb2.GetSignedBlockResponse.SerializeToString,
      ),
      'GetAccountListByBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountListByBalance,
          request_deserializer=grpc__pb2.GetAccountListByBalanceRequest.FromString,
          response_serializer=grpc__pb2.GetAccountListResponse.SerializeToString,
      ),
      'GetDailyTotalTrxInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDailyTotalTrxInfo,
          request_deserializer=grpc__pb2.GetDailyTotalTrxRequest.FromString,
          response_serializer=grpc__pb2.GetDailyTotalTrxResponse.SerializeToString,
      ),
      'GetTrxInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrxInfoById,
          request_deserializer=grpc__pb2.GetTrxInfoByIdRequest.FromString,
          response_serializer=grpc__pb2.GetTrxInfoByIdResponse.SerializeToString,
      ),
      'GetTrxListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrxListByTime,
          request_deserializer=grpc__pb2.GetTrxListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetTrxListByTimeResponse.SerializeToString,
      ),
      'GetPostListByCreateTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByCreateTime,
          request_deserializer=grpc__pb2.GetPostListByCreateTimeRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreateTimeResponse.SerializeToString,
      ),
      'GetPostListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByName,
          request_deserializer=grpc__pb2.GetPostListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreateTimeResponse.SerializeToString,
      ),
      'TrxStatByHour': grpc.unary_unary_rpc_method_handler(
          servicer.TrxStatByHour,
          request_deserializer=grpc__pb2.TrxStatByHourRequest.FromString,
          response_serializer=grpc__pb2.TrxStatByHourResponse.SerializeToString,
      ),
      'GetUserTrxListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserTrxListByTime,
          request_deserializer=grpc__pb2.GetUserTrxListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetUserTrxListByTimeResponse.SerializeToString,
      ),
      'GetPostInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostInfoById,
          request_deserializer=grpc__pb2.GetPostInfoByIdRequest.FromString,
          response_serializer=grpc__pb2.GetPostInfoByIdResponse.SerializeToString,
      ),
      'GetContractInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractInfo,
          request_deserializer=grpc__pb2.GetContractInfoRequest.FromString,
          response_serializer=grpc__pb2.GetContractInfoResponse.SerializeToString,
      ),
      'GetBlkIsIrreversibleByTxId': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlkIsIrreversibleByTxId,
          request_deserializer=grpc__pb2.GetBlkIsIrreversibleByTxIdRequest.FromString,
          response_serializer=grpc__pb2.GetBlkIsIrreversibleByTxIdResponse.SerializeToString,
      ),
      'GetAccountListByCreTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountListByCreTime,
          request_deserializer=grpc__pb2.GetAccountListByCreTimeRequest.FromString,
          response_serializer=grpc__pb2.GetAccountListResponse.SerializeToString,
      ),
      'GetDailyStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetDailyStats,
          request_deserializer=grpc__pb2.GetDailyStatsRequest.FromString,
          response_serializer=grpc__pb2.GetDailyStatsResponse.SerializeToString,
      ),
      'GetContractListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractListByTime,
          request_deserializer=grpc__pb2.GetContractListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetContractListResponse.SerializeToString,
      ),
      'GetWitnessListByVoteCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetWitnessListByVoteCount,
          request_deserializer=grpc__pb2.GetWitnessListByVoteCountRequest.FromString,
          response_serializer=grpc__pb2.GetWitnessListResponse.SerializeToString,
      ),
      'GetPostListByVest': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByVest,
          request_deserializer=grpc__pb2.GetPostListByVestRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByVestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcpb.ApiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
