# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import contentos_sdk.grpc_pb2.grpc_pb2 as grpc__pb2


class ApiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryTableContent = channel.unary_unary(
        '/grpcpb.ApiService/QueryTableContent',
        request_serializer=grpc__pb2.GetTableContentRequest.SerializeToString,
        response_deserializer=grpc__pb2.TableContentResponse.FromString,
        )
    self.GetAccountByName = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountByName',
        request_serializer=grpc__pb2.GetAccountByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.AccountResponse.FromString,
        )
    self.GetFollowerListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowerListByName',
        request_serializer=grpc__pb2.GetFollowerListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowerListByNameResponse.FromString,
        )
    self.GetFollowingListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowingListByName',
        request_serializer=grpc__pb2.GetFollowingListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowingListByNameResponse.FromString,
        )
    self.GetFollowCountByName = channel.unary_unary(
        '/grpcpb.ApiService/GetFollowCountByName',
        request_serializer=grpc__pb2.GetFollowCountByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetFollowCountByNameResponse.FromString,
        )
    self.GetBlockProducerList = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockProducerList',
        request_serializer=grpc__pb2.GetBlockProducerListRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockProducerListResponse.FromString,
        )
    self.GetPostListByCreated = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByCreated',
        request_serializer=grpc__pb2.GetPostListByCreatedRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreatedResponse.FromString,
        )
    self.GetReplyListByPostId = channel.unary_unary(
        '/grpcpb.ApiService/GetReplyListByPostId',
        request_serializer=grpc__pb2.GetReplyListByPostIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetReplyListByPostIdResponse.FromString,
        )
    self.GetBlockTransactionsByNum = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockTransactionsByNum',
        request_serializer=grpc__pb2.GetBlockTransactionsByNumRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockTransactionsByNumResponse.FromString,
        )
    self.GetChainState = channel.unary_unary(
        '/grpcpb.ApiService/GetChainState',
        request_serializer=grpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetChainStateResponse.FromString,
        )
    self.BroadcastTrx = channel.unary_unary(
        '/grpcpb.ApiService/BroadcastTrx',
        request_serializer=grpc__pb2.BroadcastTrxRequest.SerializeToString,
        response_deserializer=grpc__pb2.BroadcastTrxResponse.FromString,
        )
    self.GetBlockList = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockList',
        request_serializer=grpc__pb2.GetBlockListRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockListResponse.FromString,
        )
    self.GetSignedBlock = channel.unary_unary(
        '/grpcpb.ApiService/GetSignedBlock',
        request_serializer=grpc__pb2.GetSignedBlockRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetSignedBlockResponse.FromString,
        )
    self.GetAccountListByBalance = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountListByBalance',
        request_serializer=grpc__pb2.GetAccountListByBalanceRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAccountListResponse.FromString,
        )
    self.GetDailyTotalTrxInfo = channel.unary_unary(
        '/grpcpb.ApiService/GetDailyTotalTrxInfo',
        request_serializer=grpc__pb2.GetDailyTotalTrxRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetDailyTotalTrxResponse.FromString,
        )
    self.GetTrxInfoById = channel.unary_unary(
        '/grpcpb.ApiService/GetTrxInfoById',
        request_serializer=grpc__pb2.GetTrxInfoByIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetTrxInfoByIdResponse.FromString,
        )
    self.GetTrxListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetTrxListByTime',
        request_serializer=grpc__pb2.GetTrxListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetTrxListByTimeResponse.FromString,
        )
    self.GetPostListByCreateTime = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByCreateTime',
        request_serializer=grpc__pb2.GetPostListByCreateTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreateTimeResponse.FromString,
        )
    self.GetPostListByName = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByName',
        request_serializer=grpc__pb2.GetPostListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByCreateTimeResponse.FromString,
        )
    self.TrxStatByHour = channel.unary_unary(
        '/grpcpb.ApiService/TrxStatByHour',
        request_serializer=grpc__pb2.TrxStatByHourRequest.SerializeToString,
        response_deserializer=grpc__pb2.TrxStatByHourResponse.FromString,
        )
    self.GetUserTrxListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetUserTrxListByTime',
        request_serializer=grpc__pb2.GetUserTrxListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetUserTrxListByTimeResponse.FromString,
        )
    self.GetPostInfoById = channel.unary_unary(
        '/grpcpb.ApiService/GetPostInfoById',
        request_serializer=grpc__pb2.GetPostInfoByIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostInfoByIdResponse.FromString,
        )
    self.GetContractInfo = channel.unary_unary(
        '/grpcpb.ApiService/GetContractInfo',
        request_serializer=grpc__pb2.GetContractInfoRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetContractInfoResponse.FromString,
        )
    self.GetBlkIsIrreversibleByTxId = channel.unary_unary(
        '/grpcpb.ApiService/GetBlkIsIrreversibleByTxId',
        request_serializer=grpc__pb2.GetBlkIsIrreversibleByTxIdRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlkIsIrreversibleByTxIdResponse.FromString,
        )
    self.GetAccountListByCreTime = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountListByCreTime',
        request_serializer=grpc__pb2.GetAccountListByCreTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAccountListResponse.FromString,
        )
    self.GetDailyStats = channel.unary_unary(
        '/grpcpb.ApiService/GetDailyStats',
        request_serializer=grpc__pb2.GetDailyStatsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetDailyStatsResponse.FromString,
        )
    self.GetContractListByTime = channel.unary_unary(
        '/grpcpb.ApiService/GetContractListByTime',
        request_serializer=grpc__pb2.GetContractListByTimeRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetContractListResponse.FromString,
        )
    self.GetBlockProducerListByVoteCount = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockProducerListByVoteCount',
        request_serializer=grpc__pb2.GetBlockProducerListByVoteCountRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockProducerListResponse.FromString,
        )
    self.GetPostListByVest = channel.unary_unary(
        '/grpcpb.ApiService/GetPostListByVest',
        request_serializer=grpc__pb2.GetPostListByVestRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetPostListByVestResponse.FromString,
        )
    self.EstimateStamina = channel.unary_unary(
        '/grpcpb.ApiService/EstimateStamina',
        request_serializer=grpc__pb2.EsimateRequest.SerializeToString,
        response_deserializer=grpc__pb2.EsimateResponse.FromString,
        )
    self.GetNodeNeighbours = channel.unary_unary(
        '/grpcpb.ApiService/GetNodeNeighbours',
        request_serializer=grpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetNodeNeighboursResponse.FromString,
        )
    self.GetMyStakers = channel.unary_unary(
        '/grpcpb.ApiService/GetMyStakers',
        request_serializer=grpc__pb2.GetMyStakerListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetMyStakerListByNameResponse.FromString,
        )
    self.GetMyStakes = channel.unary_unary(
        '/grpcpb.ApiService/GetMyStakes',
        request_serializer=grpc__pb2.GetMyStakeListByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetMyStakeListByNameResponse.FromString,
        )
    self.GetNodeRunningVersion = channel.unary_unary(
        '/grpcpb.ApiService/GetNodeRunningVersion',
        request_serializer=grpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetNodeRunningVersionResponse.FromString,
        )
    self.GetAccountListByVest = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountListByVest',
        request_serializer=grpc__pb2.GetAccountListByVestRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAccountListResponse.FromString,
        )
    self.GetBlockProducerByName = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockProducerByName',
        request_serializer=grpc__pb2.GetBlockProducerByNameRequest.SerializeToString,
        response_deserializer=grpc__pb2.BlockProducerResponse.FromString,
        )
    self.GetAccountByPubKey = channel.unary_unary(
        '/grpcpb.ApiService/GetAccountByPubKey',
        request_serializer=grpc__pb2.GetAccountByPubKeyRequest.SerializeToString,
        response_deserializer=grpc__pb2.AccountResponse.FromString,
        )
    self.GetBlockBFTInfoByNum = channel.unary_unary(
        '/grpcpb.ApiService/GetBlockBFTInfoByNum',
        request_serializer=grpc__pb2.GetBlockBFTInfoByNumRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetBlockBFTInfoByNumResponse.FromString,
        )
    self.GetAppTableRecord = channel.unary_unary(
        '/grpcpb.ApiService/GetAppTableRecord',
        request_serializer=grpc__pb2.GetAppTableRecordRequest.SerializeToString,
        response_deserializer=grpc__pb2.GetAppTableRecordResponse.FromString,
        )


class ApiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def QueryTableContent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowerListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowingListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowCountByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockProducerList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByCreated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReplyListByPostId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockTransactionsByNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChainState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastTrx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSignedBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountListByBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDailyTotalTrxInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrxInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrxListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByCreateTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TrxStatByHour(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserTrxListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostInfoById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlkIsIrreversibleByTxId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountListByCreTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDailyStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractListByTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockProducerListByVoteCount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPostListByVest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EstimateStamina(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeNeighbours(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyStakers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyStakes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeRunningVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountListByVest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockProducerByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountByPubKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockBFTInfoByNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAppTableRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryTableContent': grpc.unary_unary_rpc_method_handler(
          servicer.QueryTableContent,
          request_deserializer=grpc__pb2.GetTableContentRequest.FromString,
          response_serializer=grpc__pb2.TableContentResponse.SerializeToString,
      ),
      'GetAccountByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountByName,
          request_deserializer=grpc__pb2.GetAccountByNameRequest.FromString,
          response_serializer=grpc__pb2.AccountResponse.SerializeToString,
      ),
      'GetFollowerListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowerListByName,
          request_deserializer=grpc__pb2.GetFollowerListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowerListByNameResponse.SerializeToString,
      ),
      'GetFollowingListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowingListByName,
          request_deserializer=grpc__pb2.GetFollowingListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowingListByNameResponse.SerializeToString,
      ),
      'GetFollowCountByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowCountByName,
          request_deserializer=grpc__pb2.GetFollowCountByNameRequest.FromString,
          response_serializer=grpc__pb2.GetFollowCountByNameResponse.SerializeToString,
      ),
      'GetBlockProducerList': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockProducerList,
          request_deserializer=grpc__pb2.GetBlockProducerListRequest.FromString,
          response_serializer=grpc__pb2.GetBlockProducerListResponse.SerializeToString,
      ),
      'GetPostListByCreated': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByCreated,
          request_deserializer=grpc__pb2.GetPostListByCreatedRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreatedResponse.SerializeToString,
      ),
      'GetReplyListByPostId': grpc.unary_unary_rpc_method_handler(
          servicer.GetReplyListByPostId,
          request_deserializer=grpc__pb2.GetReplyListByPostIdRequest.FromString,
          response_serializer=grpc__pb2.GetReplyListByPostIdResponse.SerializeToString,
      ),
      'GetBlockTransactionsByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockTransactionsByNum,
          request_deserializer=grpc__pb2.GetBlockTransactionsByNumRequest.FromString,
          response_serializer=grpc__pb2.GetBlockTransactionsByNumResponse.SerializeToString,
      ),
      'GetChainState': grpc.unary_unary_rpc_method_handler(
          servicer.GetChainState,
          request_deserializer=grpc__pb2.NonParamsRequest.FromString,
          response_serializer=grpc__pb2.GetChainStateResponse.SerializeToString,
      ),
      'BroadcastTrx': grpc.unary_unary_rpc_method_handler(
          servicer.BroadcastTrx,
          request_deserializer=grpc__pb2.BroadcastTrxRequest.FromString,
          response_serializer=grpc__pb2.BroadcastTrxResponse.SerializeToString,
      ),
      'GetBlockList': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockList,
          request_deserializer=grpc__pb2.GetBlockListRequest.FromString,
          response_serializer=grpc__pb2.GetBlockListResponse.SerializeToString,
      ),
      'GetSignedBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetSignedBlock,
          request_deserializer=grpc__pb2.GetSignedBlockRequest.FromString,
          response_serializer=grpc__pb2.GetSignedBlockResponse.SerializeToString,
      ),
      'GetAccountListByBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountListByBalance,
          request_deserializer=grpc__pb2.GetAccountListByBalanceRequest.FromString,
          response_serializer=grpc__pb2.GetAccountListResponse.SerializeToString,
      ),
      'GetDailyTotalTrxInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDailyTotalTrxInfo,
          request_deserializer=grpc__pb2.GetDailyTotalTrxRequest.FromString,
          response_serializer=grpc__pb2.GetDailyTotalTrxResponse.SerializeToString,
      ),
      'GetTrxInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrxInfoById,
          request_deserializer=grpc__pb2.GetTrxInfoByIdRequest.FromString,
          response_serializer=grpc__pb2.GetTrxInfoByIdResponse.SerializeToString,
      ),
      'GetTrxListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrxListByTime,
          request_deserializer=grpc__pb2.GetTrxListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetTrxListByTimeResponse.SerializeToString,
      ),
      'GetPostListByCreateTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByCreateTime,
          request_deserializer=grpc__pb2.GetPostListByCreateTimeRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreateTimeResponse.SerializeToString,
      ),
      'GetPostListByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByName,
          request_deserializer=grpc__pb2.GetPostListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByCreateTimeResponse.SerializeToString,
      ),
      'TrxStatByHour': grpc.unary_unary_rpc_method_handler(
          servicer.TrxStatByHour,
          request_deserializer=grpc__pb2.TrxStatByHourRequest.FromString,
          response_serializer=grpc__pb2.TrxStatByHourResponse.SerializeToString,
      ),
      'GetUserTrxListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserTrxListByTime,
          request_deserializer=grpc__pb2.GetUserTrxListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetUserTrxListByTimeResponse.SerializeToString,
      ),
      'GetPostInfoById': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostInfoById,
          request_deserializer=grpc__pb2.GetPostInfoByIdRequest.FromString,
          response_serializer=grpc__pb2.GetPostInfoByIdResponse.SerializeToString,
      ),
      'GetContractInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractInfo,
          request_deserializer=grpc__pb2.GetContractInfoRequest.FromString,
          response_serializer=grpc__pb2.GetContractInfoResponse.SerializeToString,
      ),
      'GetBlkIsIrreversibleByTxId': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlkIsIrreversibleByTxId,
          request_deserializer=grpc__pb2.GetBlkIsIrreversibleByTxIdRequest.FromString,
          response_serializer=grpc__pb2.GetBlkIsIrreversibleByTxIdResponse.SerializeToString,
      ),
      'GetAccountListByCreTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountListByCreTime,
          request_deserializer=grpc__pb2.GetAccountListByCreTimeRequest.FromString,
          response_serializer=grpc__pb2.GetAccountListResponse.SerializeToString,
      ),
      'GetDailyStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetDailyStats,
          request_deserializer=grpc__pb2.GetDailyStatsRequest.FromString,
          response_serializer=grpc__pb2.GetDailyStatsResponse.SerializeToString,
      ),
      'GetContractListByTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractListByTime,
          request_deserializer=grpc__pb2.GetContractListByTimeRequest.FromString,
          response_serializer=grpc__pb2.GetContractListResponse.SerializeToString,
      ),
      'GetBlockProducerListByVoteCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockProducerListByVoteCount,
          request_deserializer=grpc__pb2.GetBlockProducerListByVoteCountRequest.FromString,
          response_serializer=grpc__pb2.GetBlockProducerListResponse.SerializeToString,
      ),
      'GetPostListByVest': grpc.unary_unary_rpc_method_handler(
          servicer.GetPostListByVest,
          request_deserializer=grpc__pb2.GetPostListByVestRequest.FromString,
          response_serializer=grpc__pb2.GetPostListByVestResponse.SerializeToString,
      ),
      'EstimateStamina': grpc.unary_unary_rpc_method_handler(
          servicer.EstimateStamina,
          request_deserializer=grpc__pb2.EsimateRequest.FromString,
          response_serializer=grpc__pb2.EsimateResponse.SerializeToString,
      ),
      'GetNodeNeighbours': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeNeighbours,
          request_deserializer=grpc__pb2.NonParamsRequest.FromString,
          response_serializer=grpc__pb2.GetNodeNeighboursResponse.SerializeToString,
      ),
      'GetMyStakers': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyStakers,
          request_deserializer=grpc__pb2.GetMyStakerListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetMyStakerListByNameResponse.SerializeToString,
      ),
      'GetMyStakes': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyStakes,
          request_deserializer=grpc__pb2.GetMyStakeListByNameRequest.FromString,
          response_serializer=grpc__pb2.GetMyStakeListByNameResponse.SerializeToString,
      ),
      'GetNodeRunningVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeRunningVersion,
          request_deserializer=grpc__pb2.NonParamsRequest.FromString,
          response_serializer=grpc__pb2.GetNodeRunningVersionResponse.SerializeToString,
      ),
      'GetAccountListByVest': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountListByVest,
          request_deserializer=grpc__pb2.GetAccountListByVestRequest.FromString,
          response_serializer=grpc__pb2.GetAccountListResponse.SerializeToString,
      ),
      'GetBlockProducerByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockProducerByName,
          request_deserializer=grpc__pb2.GetBlockProducerByNameRequest.FromString,
          response_serializer=grpc__pb2.BlockProducerResponse.SerializeToString,
      ),
      'GetAccountByPubKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountByPubKey,
          request_deserializer=grpc__pb2.GetAccountByPubKeyRequest.FromString,
          response_serializer=grpc__pb2.AccountResponse.SerializeToString,
      ),
      'GetBlockBFTInfoByNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockBFTInfoByNum,
          request_deserializer=grpc__pb2.GetBlockBFTInfoByNumRequest.FromString,
          response_serializer=grpc__pb2.GetBlockBFTInfoByNumResponse.SerializeToString,
      ),
      'GetAppTableRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetAppTableRecord,
          request_deserializer=grpc__pb2.GetAppTableRecordRequest.FromString,
          response_serializer=grpc__pb2.GetAppTableRecordResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcpb.ApiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
